// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from "contentful";
import { Document } from "@contentful/rich-text-types";

export interface IBlogPostFields {
  /** Заголовок */
  title: string;

  /** slug */
  slug?: string | undefined;

  /** Короткое описание */
  short_descr?: string | undefined;

  /** Контент */
  content: Document;
}

export interface IBlogPost extends Entry<IBlogPostFields> {
  fields: any;
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "blogPost";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export type CONTENT_TYPE = "blogPost";

export type IEntry = IBlogPost;

export type LOCALE_CODE = "en-US";

export type CONTENTFUL_DEFAULT_LOCALE_CODE = "en-US";

export function createClient(arg0: { space: string; accessToken: string }) {
  throw new Error("Function not implemented.");
}
