import { Box } from "@chakra-ui/layout";
import { GetStaticProps } from "next";
import Head from "next/head";
import { Container } from "@chakra-ui/react";
import { documentToReactComponents } from "@contentful/rich-text-react-renderer";

import client from "../../contentful-ts/index";
import React from "react";
import Link from "next/link";

export default function Home({ posts }): JSX.Element {
  return (
    <>
      <Head>
        <title>Blogium</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="bg">
          <Container centerContent>
            <Box pt={10} pb={10} textAlign="center" fontSize={36} color="white">
              <h1>Blogium</h1>
            </Box>
          </Container>
        </div>

        <Container mt={10} gap="2">
          {posts?.map((post) => {
            return (
              <React.Fragment key={post?.fields.slug}>
                <Box maxW="700px" mb={5}>
                  <Link
                    className="post_link"
                    href={`posts/${post?.fields.slug}`}
                  >
                    <h1 className="post_title">{post?.fields.title}</h1>
                    <h3 className="post_subtitle">
                      {post?.fields.short_descr}
                    </h3>
                  </Link>
                  <p className="post-meta">Posted by Admin on July 8, 2023</p>
                </Box>
                <hr className="post_hr" />
              </React.Fragment>
            );
          })}
        </Container>
      </main>

      <hr className="post_hr" />

      <footer className="post_footer">
        <div className="post-footer-container">
          <p className="footer-text">Copyright © All Rights Reserved</p>
        </div>
      </footer>
    </>
  );
}

export const getStaticProps: GetStaticProps = async () => {
  const posts = await client.getEntries({
    content_type: "blogPost",
    select: "fields.title,fields.slug,fields.short_descr",
  });

  return {
    props: { posts: posts.items },
    revalidate: 3600,
  };
};
